# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'new-connection'
    subscriptionId: '036c9523-22ed-4407-84de-37ce553b4d7e'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'WinRMTest'
    location: 'North Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/ziyadalrasbi/AzureRmPipeline-repo/master/CreateWebApp/azuredeploy.json'
    deploymentMode: 'Incremental'
    deploymentName: 'ArmDeploy'