# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Free Trial(bea02a17-caaa-4a8f-9f4a-3cc4b647bb1a)'
    subscriptionId: 'bea02a17-caaa-4a8f-9f4a-3cc4b647bb1a'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Test'
    location: 'North Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/ziyadalrasbi/AzureRmPipeline-repo/master/CreateWebApp/azuredeploy.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/ziyadalrasbi/AzureRmPipeline-repo/master/CreateWebApp/azuredeploy.parameters.json'
    overrideParameters: |
      -adminUsername elielmal
      -adminPasswordOrKey Allezparis21
      -PlatformSelection Linux
    deploymentMode: 'Incremental'
    deploymentName: 'ArmDeployement1'